### ISSUE TITLE
name correction suggestion for [http://arctos.database.museum/guid/MSB:Host:16891]

### ISSUE THREAD

**Issue by arw36** [globalbioticinteractions/globi-taxon-names#7] opened 2021-05-02 19:17 UTC
Hi!
I found a taxon name ```http://arctos.database.museum/guid/MSB:Host:16891``` on a [globi page](https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=NCBI%3A6211). After reviewing the data sources and relevant taxonomic tools like the [globalnames resolver](https://resolver.globalnames.org), I think that suggestion below might be helpful.

 Thanks!

| name | suggested name | name url reference | notes
| --- | --- | --- | ---
| http://arctos.database.museum/guid/MSB:Host:16891 | Microtus oeconomus | https://eol.org/pages/1037789 | host given on ARCTOS website

**Comment by jhpoelen** [comment] 2021-05-03 20:28
hi Anna @arw36 - thanks for submitting your name correction suggestion. The root cause for GloBI not resolving the names related to the host record http://arctos.database.museum/guid/MSB:Host:16891 is that the dependencies of the https://github.com/globalbioticinteractions/msb-para configuration are not yet defined. 

I've opened a separate issue on this at https://github.com/globalbioticinteractions/msb-para/issues/1 . Once this issue is resolved, your suggested name correction should be automatically be performed.

**Comment by jhpoelen** [comment] 2021-05-20 18:25
Suggested name _Microtus oeconomus_  related to http://arctos.database.museum/guid/MSB:Host:16891 is now being shown as expected. See attached screenshot of https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FMSB%3AHost%3A16891&interactionType=interactsWith . 

![Screenshot from 2021-05-20 11-24-04](https://user-images.githubusercontent.com/1084872/119029803-f8ab3900-b95d-11eb-8e22-fa359a6d8e8f.png)

Also see https://github.com/globalbioticinteractions/msb-para/issues/1#issuecomment-845357452 .

Note that unresolved MSB Para name references will no longer appear after the deprecation of https://github.com/globalbioticinteractions/msb-host has propagated.

**Closed as completed by jhpoelen** 2021-05-20 18:25 UTC
